import 'dotenv/config'
import { PrismaClient, Role, TechnologyDomain, InquiryType, InquiryStatus, PartnerType, DocumentCategory } from '@prisma/client'
import { PrismaPg } from '@prisma/adapter-pg'
import bcrypt from 'bcryptjs'

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! })
const prisma = new PrismaClient({ adapter })

async function main() {
  console.log('Seeding database...')

  const h1 = await bcrypt.hash('Admin@123', 10)
  const h2 = await bcrypt.hash('Editor@123', 10)
  const admin = await prisma.user.upsert({ where: { email: 'admin@swatek.tech' }, update: {}, create: { name: 'Admin', email: 'admin@swatek.tech', passwordHash: h1, role: Role.admin } })
  const editor = await prisma.user.upsert({ where: { email: 'editor@swatek.tech' }, update: {}, create: { name: 'Editor', email: 'editor@swatek.tech', passwordHash: h2, role: Role.editor } })
  console.log('users ok')

  const dAI    = await prisma.technologyDomainRecord.upsert({ where: { domain: TechnologyDomain.AI }, update: {}, create: { slug: 'artificial-intelligence', domain: TechnologyDomain.AI, nameEn: 'Artificial Intelligence', nameFr: 'Intelligence Artificielle', nameAr: 'الذكاء الاصطناعي', descEn: 'AI analytics and predictive systems.', descFr: 'Analytique IA.', descAr: 'تحليلات الذكاء الاصطناعي.', icon: 'Brain' } })
  const dInd   = await prisma.technologyDomainRecord.upsert({ where: { domain: TechnologyDomain.INDUSTRY_40 }, update: {}, create: { slug: 'industry-40', domain: TechnologyDomain.INDUSTRY_40, nameEn: 'Industry 4.0', nameFr: 'Industrie 4.0', nameAr: 'الصناعة 4.0', descEn: 'Smart manufacturing and IIoT.', descFr: 'Fabrication intelligente.', descAr: 'التصنيع الذكي.', icon: 'Factory' } })
  const dCirc  = await prisma.technologyDomainRecord.upsert({ where: { domain: TechnologyDomain.CIRCULAR_ECONOMY }, update: {}, create: { slug: 'circular-economy', domain: TechnologyDomain.CIRCULAR_ECONOMY, nameEn: 'Circular Economy', nameFr: 'Economie Circulaire', nameAr: 'الاقتصاد الدائري', descEn: 'Waste valorization and zero-waste cycles.', descFr: 'Valorisation dechets.', descAr: 'تثمين النفايات.', icon: 'Recycle' } })
  const dEnerg = await prisma.technologyDomainRecord.upsert({ where: { domain: TechnologyDomain.ENERGY_HYDROGEN }, update: {}, create: { slug: 'energy-hydrogen', domain: TechnologyDomain.ENERGY_HYDROGEN, nameEn: 'Energy and Hydrogen', nameFr: 'Energie et Hydrogene', nameAr: 'الطاقة والهيدروجين', descEn: 'Clean energy and green hydrogen.', descFr: 'Energie propre et hydrogene vert.', descAr: 'الطاقة النظيفة.', icon: 'Zap' } })
  const dAgro  = await prisma.technologyDomainRecord.upsert({ where: { domain: TechnologyDomain.AGRICULTURE_40 }, update: {}, create: { slug: 'agriculture-40', domain: TechnologyDomain.AGRICULTURE_40, nameEn: 'Agriculture 4.0', nameFr: 'Agriculture 4.0', nameAr: 'الزراعة 4.0', descEn: 'Precision farming and smart aquaculture.', descFr: 'Agriculture de precision.', descAr: 'الزراعة الدقيقة.', icon: 'Sprout' } })
  const dInfra = await prisma.technologyDomainRecord.upsert({ where: { domain: TechnologyDomain.SMART_INFRASTRUCTURE }, update: {}, create: { slug: 'smart-infrastructure', domain: TechnologyDomain.SMART_INFRASTRUCTURE, nameEn: 'Smart Infrastructure', nameFr: 'Infrastructure Intelligente', nameAr: 'البنية التحتية الذكية', descEn: 'Smart buildings and BMS.', descFr: 'Batiments intelligents.', descAr: 'المباني الذكية.', icon: 'Building2' } })
  console.log('domains ok')

  const t1 = await prisma.technology.upsert({ where: { slug: 'smart-energy-management' }, update: {}, create: { slug: 'smart-energy-management', domainId: dEnerg.id, nameEn: 'Smart Energy Management System (SEMS)', nameFr: 'Systeme de Gestion Intelligente de Energie', nameAr: 'نظام إدارة الطاقة الذكي', descEn: 'Real-time energy monitoring and optimization platform.', descFr: 'Surveillance energie temps reel.', descAr: 'منصة مراقبة وتحسين الطاقة.', benefitsEn: ['35% energy cost reduction', 'Real-time anomaly detection'], benefitsFr: ['Reduction 35%'], benefitsAr: ['خفض 35%'], energySavingsPct: 35, carbonReductionPct: 28, roiPeriodMonths: 18, tags: ['energy', 'IoT', 'analytics'], featured: true } })
  const t2 = await prisma.technology.upsert({ where: { slug: 'smart-manufacturing' }, update: {}, create: { slug: 'smart-manufacturing', domainId: dInd.id, nameEn: 'Smart Manufacturing Platform', nameFr: 'Plateforme Fabrication Intelligente', nameAr: 'منصة التصنيع الذكي', descEn: 'Connected factory with digital twins and AI quality control.', descFr: 'Usine connectee et jumeaux numeriques.', descAr: 'مصنع متصل مع التوائم الرقمية.', benefitsEn: ['20% OEE increase', '40% downtime reduction'], benefitsFr: ['20% TRS'], benefitsAr: ['زيادة 20%'], energySavingsPct: 22, carbonReductionPct: 18, roiPeriodMonths: 24, tags: ['manufacturing', 'IIoT', 'digital-twin'], featured: true } })
  const t3 = await prisma.technology.upsert({ where: { slug: 'precision-farming' }, update: {}, create: { slug: 'precision-farming', domainId: dAgro.id, nameEn: 'Precision Farming System', nameFr: 'Systeme Agriculture de Precision', nameAr: 'نظام الزراعة الدقيقة', descEn: 'Drone imaging, soil sensors, AI irrigation scheduling.', descFr: 'Imagerie drone et irrigation IA.', descAr: 'طائرات مسيرة وري ذكي.', benefitsEn: ['30% yield increase', '40% less water'], benefitsFr: ['30% rendements'], benefitsAr: ['زيادة 30%'], energySavingsPct: 15, carbonReductionPct: 25, roiPeriodMonths: 30, tags: ['agriculture', 'drone', 'AI'], featured: true } })
  const t4 = await prisma.technology.upsert({ where: { slug: 'smart-aquaculture' }, update: {}, create: { slug: 'smart-aquaculture', domainId: dAgro.id, nameEn: 'Smart Aquaculture Platform', nameFr: 'Plateforme Aquaculture Intelligente', nameAr: 'منصة الاستزراع المائي الذكي', descEn: 'Water quality monitoring and AI fish health diagnostics.', descFr: 'Surveillance eau et diagnostics poissons.', descAr: 'مراقبة المياه وتشخيصات صحة الأسماك.', benefitsEn: ['25% survival improvement'], benefitsFr: ['25% survie'], benefitsAr: ['تحسين 25%'], energySavingsPct: 20, carbonReductionPct: 15, roiPeriodMonths: 20, tags: ['aquaculture', 'IoT', 'water-quality'] } })
  const t5 = await prisma.technology.upsert({ where: { slug: 'waste-valorization' }, update: {}, create: { slug: 'waste-valorization', domainId: dCirc.id, nameEn: 'Organic Waste Valorization', nameFr: 'Valorisation Dechets Organiques', nameAr: 'تثمين النفايات العضوية', descEn: 'Anaerobic digestion converting waste to biogas and compost.', descFr: 'Digestion anaerobie, biogaz et compost.', descAr: 'هضم لاهوائي وتحويل إلى غاز حيوي.', benefitsEn: ['90% landfill diversion', '60% fuel replacement'], benefitsFr: ['90% dechets'], benefitsAr: ['تحويل 90%'], energySavingsPct: 45, carbonReductionPct: 60, roiPeriodMonths: 36, tags: ['waste', 'biogas', 'circular'] } })
  const t6 = await prisma.technology.upsert({ where: { slug: 'smart-building-bms' }, update: {}, create: { slug: 'smart-building-bms', domainId: dInfra.id, nameEn: 'Smart Building Management System (BMS)', nameFr: 'Systeme GTB Intelligent', nameAr: 'نظام إدارة المباني الذكي', descEn: 'Unified BMS with HVAC optimization and digital twins.', descFr: 'GTB unifie HVAC et jumeaux numeriques.', descAr: 'نظام مباني موحد مع تحسين التكييف.', benefitsEn: ['30% HVAC savings', 'Predictive fault detection'], benefitsFr: ['30% HVAC'], benefitsAr: ['توفير 30%'], energySavingsPct: 30, carbonReductionPct: 35, roiPeriodMonths: 22, tags: ['BMS', 'HVAC', 'smart-building'], featured: true } })
  const t7 = await prisma.technology.upsert({ where: { slug: 'green-hydrogen' }, update: {}, create: { slug: 'green-hydrogen', domainId: dEnerg.id, nameEn: 'Green Hydrogen Production', nameFr: 'Production Hydrogene Vert', nameAr: 'إنتاج الهيدروجين الأخضر', descEn: 'Renewable-powered electrolysis for zero-carbon hydrogen.', descFr: 'Electrolyse renouvelable, hydrogene zero carbone.', descAr: 'التحليل الكهربائي بالطاقة المتجددة.', benefitsEn: ['Zero direct emissions'], benefitsFr: ['Zero emissions'], benefitsAr: ['صفر انبعاثات'], carbonReductionPct: 95, roiPeriodMonths: 48, tags: ['hydrogen', 'renewable', 'clean-energy'], featured: true } })
  console.log('technologies ok')

  const sol1 = await prisma.solution.upsert({ where: { slug: 'industrial-decarbonization' }, update: {}, create: { slug: 'industrial-decarbonization', titleEn: 'Industrial Decarbonization Suite', titleFr: 'Suite Decarbonisation Industrielle', titleAr: 'حزمة إزالة الكربون الصناعية', descEn: 'SEMS, green hydrogen, and waste valorization for net-zero operations.', descFr: 'SEMS, hydrogene vert et valorisation dechets.', descAr: 'إدارة الطاقة والهيدروجين وتثمين النفايات.', sector: 'Heavy Industry' } })
  await prisma.solutionTechnology.createMany({ skipDuplicates: true, data: [{ solutionId: sol1.id, technologyId: t1.id }, { solutionId: sol1.id, technologyId: t7.id }, { solutionId: sol1.id, technologyId: t5.id }] })
  const sol2 = await prisma.solution.upsert({ where: { slug: 'smart-agrifood' }, update: {}, create: { slug: 'smart-agrifood', titleEn: 'Smart AgriFood Platform', titleFr: 'Plateforme AgroAlimentaire Intelligente', titleAr: 'منصة الغذاء الزراعي الذكي', descEn: 'End-to-end food production digitalization.', descFr: 'Numerisation production alimentaire.', descAr: 'رقمنة شاملة لإنتاج الغذاء.', sector: 'Agriculture and Food' } })
  await prisma.solutionTechnology.createMany({ skipDuplicates: true, data: [{ solutionId: sol2.id, technologyId: t3.id }, { solutionId: sol2.id, technologyId: t4.id }, { solutionId: sol2.id, technologyId: t5.id }] })
  console.log('solutions ok')

  await prisma.caseStudy.upsert({ where: { slug: 'steel-plant-energy' }, update: {}, create: { slug: 'steel-plant-energy', titleEn: 'Steel Plant Energy Optimization - Annaba', titleFr: 'Optimisation Energetique Acierie - Annaba', titleAr: 'تحسين طاقة مصنع الصلب - عنابة', descEn: 'SEMS at 2 GW steel complex with 1200 IoT sensors cut energy costs 31%.', descFr: 'SEMS complexe siderurgique 2 GW.', descAr: 'SEMS في مجمع صلب 2 جيجاواط.', sector: 'Heavy Industry', geography: 'Algeria', tags: ['energy', 'steel', 'IoT'], productivityGainPct: 15, carbonReductionTons: 45000, roiPct: 210, opCostReductionPct: 31, solutionId: sol1.id } })
  await prisma.caseStudy.upsert({ where: { slug: 'aquaculture-oran' }, update: {}, create: { slug: 'aquaculture-oran', titleEn: 'Precision Aquaculture - Oran Coastal Farm', titleFr: 'Aquaculture Precision - Oran', titleAr: 'الاستزراع المائي الدقيق - وهران', descEn: '50-basin fish farm with AI monitoring. Mortality dropped from 18% to 4%.', descFr: 'Ferme 50 bassins, mortalite 18% a 4%.', descAr: 'مزرعة 50 حوضا. الوفيات من 18% الى 4%.', sector: 'Aquaculture', geography: 'Algeria', tags: ['aquaculture', 'IoT'], productivityGainPct: 25, carbonReductionTons: 1200, roiPct: 180, opCostReductionPct: 22, solutionId: sol2.id } })
  await prisma.caseStudy.upsert({ where: { slug: 'waste-to-energy-setif' }, update: {}, create: { slug: 'waste-to-energy-setif', titleEn: 'Municipal Waste-to-Energy - Setif', titleFr: 'Valorisation Dechets Municipaux - Setif', titleAr: 'محطة تحويل النفايات - سطيف', descEn: '5 MW biogas plant processing 120 t/day municipal waste for 8000 homes.', descFr: 'Centrale biogaz 5 MW, 120 t/jour.', descAr: 'محطة غاز حيوي 5 ميجاواط.', sector: 'Waste Management', geography: 'Algeria', tags: ['waste-to-energy', 'biogas'], capacityMW: 5, carbonReductionTons: 28000, roiPct: 165 } })
  console.log('case studies ok')

  await prisma.knowledgeDocument.createMany({ skipDuplicates: true, data: [{ titleEn: 'SEMS White Paper', titleFr: 'Livre Blanc SEMS', titleAr: 'الورقة البيضاء SEMS', descEn: 'Architecture and AI models of the SEMS platform.', descFr: 'Architecture SEMS.', descAr: 'بنية SEMS.', category: DocumentCategory.whitepaper, language: 'en', fileType: 'pdf', pageCount: 28, fileUrl: '/uploads/documents/sems-whitepaper-en.pdf', tags: ['energy', 'SEMS'] }, { titleEn: 'Smart Agriculture Guide', titleFr: 'Guide Agriculture Intelligente', titleAr: 'دليل الزراعة الذكية', descEn: 'Deployment guide for precision farming.', descFr: 'Guide deploiement agriculture.', descAr: 'دليل الزراعة الدقيقة.', category: DocumentCategory.technical_spec, language: 'fr', fileType: 'pdf', pageCount: 42, fileUrl: '/uploads/documents/smart-agri-guide-fr.pdf', tags: ['agriculture'] }] })
  await prisma.partner.createMany({ skipDuplicates: true, data: [{ name: 'CDTA', descEn: 'Algerian AI and IoT research institution.', descFr: 'Institut recherche IA.', descAr: 'مؤسسة بحثية.', website: 'https://www.cdta.dz', type: PartnerType.academic, featured: true }, { name: 'Algerian Energy Company (AEC)', descEn: 'Clean energy financing partner.', descFr: 'Financement energie propre.', descAr: 'شريك تمويل.', type: PartnerType.financial, featured: true }, { name: 'EcoTech Solutions GmbH', descEn: 'Bioconversion and anaerobic digestion systems.', descFr: 'Systemes digestion anaerobie.', descAr: 'انظمة تحويل حيوي.', website: 'https://www.ecotech-solutions.de', type: PartnerType.technology }] })
  await prisma.impactMetric.createMany({ data: [{ labelEn: 'CO2 Avoided', labelFr: 'CO2 Evite', labelAr: 'CO2 المتجنب', value: 125000, unit: 'tonnes/year' }, { labelEn: 'Energy Saved', labelFr: 'Energie Economisee', labelAr: 'الطاقة الموفرة', value: 380, unit: 'GWh/year' }, { labelEn: 'Clients Served', labelFr: 'Clients Servis', labelAr: 'العملاء', value: 47, unit: 'organizations' }, { labelEn: 'Waste Valorized', labelFr: 'Dechets Valorises', labelAr: 'النفايات المثمنة', value: 95000, unit: 'tonnes/year' }] })
  await prisma.inquiry.createMany({ data: [{ fullName: 'Karim Benali', organization: 'Groupe Industriel de lEst', email: 'k.benali@gie.dz', phone: '+213 21 000001', inquiryType: InquiryType.technical_consulting, message: 'Reduce energy costs in cement plant via SEMS.', status: InquiryStatus.in_review, assignedToId: editor.id }, { fullName: 'Sofia Martinez', organization: 'EuroFund Capital', email: 'sofia.m@eurofund.eu', inquiryType: InquiryType.investment, message: 'Exploring co-investment in North African green hydrogen.', status: InquiryStatus.new }, { fullName: 'Youcef Hamidi', organization: 'Commune de Biskra', email: 'y.hamidi@biskra.dz', inquiryType: InquiryType.government_relation, message: 'Smart waste management for 80000 residents.', status: InquiryStatus.assigned, assignedToId: editor.id }] })
  console.log('Seed complete.')
}

main()
  .then(async () => {
    await prisma.$disconnect()
    process.exit(0)
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })